--Exploring all Objects in database
SELECT * FROM INFORMATION_SCHEMA.TABLES

--Exploring all Columns 
SELECT 
    COLUMN_NAME, 
    DATA_TYPE, 
    IS_NULLABLE, 
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';